// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/ForumPost.dart';
import 'models/PostReply.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 967020093646934196),
      name: 'ForumPost',
      lastPropertyId: const IdUid(3, 2641664069162848168),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1108933438528768628),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1113066729809350827),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2641664069162848168),
            name: 'draft',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'replies', srcEntity: 'PostReply', srcField: '')
      ]),
  ModelEntity(
      id: const IdUid(2, 3161534090598324491),
      name: 'PostReply',
      lastPropertyId: const IdUid(4, 7371925780276804914),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8459829251412716163),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 3952050065002741276),
            name: 'postId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 8224203062724588113),
            relationTarget: 'ForumPost'),
        ModelProperty(
            id: const IdUid(4, 7371925780276804914),
            name: 'content',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(3, 4006193552445279488),
            name: 'replies',
            targetId: const IdUid(2, 3161534090598324491))
      ],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3161534090598324491),
      lastIndexId: const IdUid(1, 8224203062724588113),
      lastRelationId: const IdUid(3, 4006193552445279488),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [4135032994772201769],
      retiredRelationUids: const [4955803548666071923, 7732731541165926664],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ForumPost: EntityDefinition<ForumPost>(
        model: _entities[0],
        toOneRelations: (ForumPost object) => [],
        toManyRelations: (ForumPost object) => {
              RelInfo<PostReply>.toOneBacklink(
                      3, object.id, (PostReply srcObject) => srcObject.post):
                  object.replies
            },
        getId: (ForumPost object) => object.id,
        setId: (ForumPost object, int id) {
          object.id = id;
        },
        objectToFB: (ForumPost object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addBool(2, object.draft);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ForumPost(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              draft: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 8, false));
          InternalToManyAccess.setRelInfo<ForumPost>(
              object.replies,
              store,
              RelInfo<PostReply>.toOneBacklink(
                  3, object.id, (PostReply srcObject) => srcObject.post));
          return object;
        }),
    PostReply: EntityDefinition<PostReply>(
        model: _entities[1],
        toOneRelations: (PostReply object) => [object.post],
        toManyRelations: (PostReply object) =>
            {RelInfo<PostReply>.toMany(3, object.id): object.replies},
        getId: (PostReply object) => object.id,
        setId: (PostReply object, int id) {
          object.id = id;
        },
        objectToFB: (PostReply object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.post.targetId);
          fbb.addOffset(3, contentOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PostReply(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          object.post.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.post.attach(store);
          InternalToManyAccess.setRelInfo<PostReply>(
              object.replies, store, RelInfo<PostReply>.toMany(3, object.id));
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ForumPost] entity fields to define ObjectBox queries.
class ForumPost_ {
  /// see [ForumPost.id]
  static final id = QueryIntegerProperty<ForumPost>(_entities[0].properties[0]);

  /// see [ForumPost.title]
  static final title =
      QueryStringProperty<ForumPost>(_entities[0].properties[1]);

  /// see [ForumPost.draft]
  static final draft =
      QueryBooleanProperty<ForumPost>(_entities[0].properties[2]);
}

/// [PostReply] entity fields to define ObjectBox queries.
class PostReply_ {
  /// see [PostReply.id]
  static final id = QueryIntegerProperty<PostReply>(_entities[1].properties[0]);

  /// see [PostReply.post]
  static final post =
      QueryRelationToOne<PostReply, ForumPost>(_entities[1].properties[1]);

  /// see [PostReply.content]
  static final content =
      QueryStringProperty<PostReply>(_entities[1].properties[2]);

  /// see [PostReply.replies]
  static final replies =
      QueryRelationToMany<PostReply, PostReply>(_entities[1].relations[0]);
}
